[package]
name = "common-log-format"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
http = "0.2"

[dev-dependencies]
serde_json = "1"
